name: PyLint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install pylint pytest pytest-cov

    - name: Check PyLint score
      run: |
        pylint_score=$(pylint --output-format=text --rcfile=.pylintrc --fail-under=9 ./**/*.py || echo "FAILED")
        if [[ "$pylint_score" != *"FAILED"* ]]; then
          echo "PyLint score is above 9: $pylint_score"
        else
          echo "PyLint score is below 9: $pylint_score"
          exit 0
        fi

    - name: Check Pytest coverage
      run: |
        pytest_coverage=$(pytest --cov=./ --cov=term-missing --cov-fail-under=80 tests/ || echo "FAILED")
        if [[ "$pytest_coverage" != *"FAILED"* ]]; then
              echo "Pytest coverage is above 80%: $pytest_coverage"
            else
              echo "Pytest coverage is below 80%: $pytest_coverage"
              exit 0
            fi


