name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: pip install pylint pytest pytest-cov
    - name: Run PyLint and generate report
      run: |
        pylint --output-format=.coverage --fail-under=9 ./**/*.py > pylint_report.coverage || echo "FAILED"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          token: ${{ secrets.YOUR_SECRET_TOKEN }}

    # - name: Upload coverage reports to Codecov
    #   run: |
    #     # Replace `linux` below with the appropriate OS
    #     # Options are `alpine`, `linux`, `macos`, `windows`
    #     curl -Os https://uploader.codecov.io/latest/linux/codecov
    #     chmod +x codecov
    #     ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f pylint_report.txt