name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: pip install pylint pytest pytest-cov pylint-json-report pylint-viewer
    - name: Run Pytest with coverage
      run: |
        pytest --cov .

    - name: Upload pytest coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }}

    - name: Run PyLint and generate report
      run: |
        pylint --output-format=json . > pylint_report.json
        pylint-json-report pylint_report.json > viewer_input.json
        pylint-viewer viewer_input.json

    - name: View pylint report
      run: cat pylint_coverage.txt

    - name: Upload pylint report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: viewer_input.json
